const copies={after:['나일론 소재의 데일리 미니백','외출 소지품을 담는 4L 수납공간','가벼운 물방울을 튕겨내는 발수 가공','세탁 불가 — 구매 전 관리 방법을 확인해주세요.'],before:['고급 가죽 소재의 미니백','노트북까지 넉넉하게 수납','비 오는 날에도 완벽 방수','세탁기에 넣어 간편하게 관리']};
const reasons={after:['소재를 바로잡고, 확인되지 않은 ‘구김 없음’ 표현도 제외했습니다.','노트북 수납 가능성을 단정하지 않고, 제공된 용량으로 설명했습니다.','발수 기능을 ‘완벽 방수’로 확대하지 않았습니다.','구매 전 알아야 할 관리 제한사항을 명확하게 표시했습니다.'],before:['원본의 나일론과 다른 소재를 기재한 오류입니다.','치수와 용량만으로 노트북 수납을 보장할 수 없습니다.','제공된 발수 기능보다 성능을 과장한 표현입니다.','세탁 불가라는 관리 조건과 반대되는 설명입니다.']};
function setVersion(version){document.querySelectorAll('[data-version]').forEach(b=>{const active=b.dataset.version===version;b.setAttribute('aria-selected',String(active));b.tabIndex=active?0:-1;});document.querySelectorAll('[data-copy]').forEach(el=>{el.textContent=copies[version][Number(el.dataset.copy)]});document.querySelectorAll('[data-reason]').forEach(el=>{el.textContent=reasons[version][Number(el.dataset.reason)]});document.querySelector('.review-panel').classList.toggle('is-before',version==='before');document.querySelector('#copy-panel').setAttribute('aria-labelledby',`tab-${version}`);}
document.querySelectorAll('[data-version]').forEach(b=>{b.addEventListener('click',()=>setVersion(b.dataset.version));b.addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','Home','End'].includes(e.key)){e.preventDefault();const version=e.key==='Home'?'before':e.key==='End'?'after':b.dataset.version==='before'?'after':'before';setVersion(version);document.querySelector(`[data-version="${version}"]`).focus();}})});
const dialog=document.querySelector('#image-dialog');let opener;
document.querySelectorAll('[data-image]').forEach(button=>button.addEventListener('click',()=>{opener=button;document.querySelector('#dialog-title').textContent=button.dataset.title;document.querySelector('#dialog-description').textContent=button.dataset.description;const img=document.querySelector('#dialog-image');img.src=button.dataset.image;img.alt=button.dataset.title;dialog.showModal();document.body.classList.add('no-scroll');dialog.scrollTop=0;document.querySelector('#close-dialog').focus();}));
document.querySelector('#close-dialog').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close();}});dialog.addEventListener('close',()=>{document.body.classList.remove('no-scroll');opener?.focus();});
document.querySelector('#print').addEventListener('click',()=>{setVersion('after');window.print();});
window.addEventListener('beforeprint',()=>setVersion('after'));
